name: mobile
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  protobuf: ^3.0.0

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  photo_manager: ^3.5.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  protoc_builder: ^0.4.1
  build: ^2.4.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
